---
platform: prometheus_sensor
url: http://192.168.1.133:9090
queries:
  - name: sonarr_episode_unmonitored_total
    expr: sonarr_episode_unmonitored_total
    unit_of_measurement: Episodes
    # device_class: energy
    state_class: measurement
