reset_cost:
  target:
    entity:
      domain: sensor
calibrate:
  target:
    entity:
      domain: sensor
      integration: utility_meter
  fields:
    value:
      example: "100"
      required: true
      selector:
        text: