---
# This file bootstraps the system
# Have a look inside the Integrations and Entities folders for my config

homeassistant:
  packages: !include_dir_named "integrations"
  customize: !include customisations/entities.yaml
  customize_glob: !include customisations/glob.yaml
  allowlist_external_dirs:
    - /config/
