---
homeassistant:
  packages: !include_dir_named /config/integrations
  # customize: !include /config/customisations/entities.yaml
  # customize_glob: !include /config/customisations/glob.yaml
  allowlist_external_dirs:
    - /config/
  allowlist_external_urls:
    - https://lh3.googleusercontent.com
    - https://www.gstatic.com
    - https://i.ytimg.com
    - http://cdn-radiotime-logos.tunein.com
    - https://cdn-radiotime-logos.tunein.com
