---
homeassistant:
  packages: !include_dir_named integrations
  customize: !include customisations/entities.yaml
  customize_glob: !include customisations/glob.yaml
  allowlist_external_dirs:
    - /config/
  allowlist_external_urls:
    - https://lh3.googleusercontent.com
    - https://www.gstatic.com
    - https://i.ytimg.com
    - http://cdn-radiotime-logos.tunein.com
    - https://cdn-radiotime-logos.tunein.com
