---
id: 07a2a553-83e0-487a-a751-e59a0f13a167
alias: "[TVGuide] XMLTV Process Webgrab+"
description: "[TVGuide] Process Webgrab+"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /2
# condition:
#   - condition: state
#     entity_id: input_boolean.ha_startup_pending
#     state: "off"
#     for:
#       hours: 0
#       minutes: 0
#       seconds: 30
action:
  - service: shell_command.xmltv_getfromwebgrabplus
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: pyscript.process_tvguide
    data:
      file: /config/xmltv/webgrabplus.xml
  - service: pyscript.getdata_tvguide_optussport
    data: {}
