---
alias: "[TVGuide] XMLTV Download"
description: "[TVGuide] XMLTV Download"
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: "01:00:00"
condition:
  - condition: state
    entity_id: input_boolean.ha_startup_pending
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: pyscript.download_xmltv
    data:
      url: https://i.mjh.nz/Optus/epg.xml
      statussensor: sensor.tvguide_xmltv_status_optussport
      filename: optus_sport.xml
      sensorname: Optus Sport
