---
alias: "[Sonos Favourites] Play ABC News"
description: Play ABC News on Sonos
id: sonos_favourites_play_abc_news
trigger:
  - platform: webhook
    webhook_id: sonos_abc_news
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_abc_news
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC News"
