---
alias: "[Sonos Favourites] Play ABC Radio National (Sydney, NSW)"
description: Play ABC Radio National (Sydney, NSW) on Sonos
id: sonos_favourites_play_abc_radio_national_sydney_nsw
trigger:
  - platform: webhook
    webhook_id: sonos_abc_radio_national_sydney_nsw
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_abc_radio_national_sydney_nsw
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "ABC Radio National (Sydney, NSW)"
