---
alias: "[Sonos Favourites] Play Absolute Radio 80s"
description: Play Absolute Radio 80s on Sonos
id: sonos_favourites_play_absolute_radio_80s
trigger:
  - platform: webhook
    webhook_id: sonos_absolute_radio_80s
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_absolute_radio_80s
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Absolute Radio 80s"
