---
alias: "[Sonos Favourites] Play BBC Radio 5 live sports extra"
description: Play BBC Radio 5 live sports extra on Sonos
id: sonos_favourites_play_bbc_radio_5_live_sports_extra
trigger:
  - platform: webhook
    webhook_id: sonos_bbc_radio_5_live_sports_extra
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_bbc_radio_5_live_sports_extra
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "BBC Radio 5 live sports extra"
