---
alias: "[Sonos Favourites] Play Gaydio (London) (Top 40 & Pop Music)"
description: Play Gaydio (London) (Top 40 & Pop Music) on Sonos
id: sonos_favourites_play_gaydio_london_top_40_pop_music
trigger:
  - platform: webhook
    webhook_id: sonos_gaydio_london_top_40_pop_music
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_gaydio_london_top_40_pop_music
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Gaydio (London) (Top 40 & Pop Music)"
