---
alias: "[Sonos Favourites] Play GB News Radio (Local News)"
description: Play GB News Radio (Local News) on Sonos
id: sonos_favourites_play_gb_news_radio_local_news
trigger:
  - platform: webhook
    webhook_id: sonos_gb_news_radio_local_news
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_gb_news_radio_local_news
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "GB News Radio (Local News)"
