---
alias: "[Sonos Favourites] Play GOLD 104.3"
description: Play GOLD 104.3 on Sonos
id: sonos_favourites_play_gold_104_3
trigger:
  - platform: webhook
    webhook_id: sonos_gold_104_3
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_gold_104_3
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "GOLD 104.3"
