---
alias: "[Sonos Favourites] Play Nova Throwbacks"
description: Play Nova Throwbacks on Sonos
id: sonos_favourites_play_nova_throwbacks
trigger:
  - platform: webhook
    webhook_id: sonos_nova_throwbacks
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_nova_throwbacks
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova Throwbacks"
