---
alias: "[Sonos Favourites] Play Nova Nation"
description: Play Nova Nation on Sonos
id: sonos_favourites_play_nova_nation
trigger:
  - platform: webhook
    webhook_id: sonos_nova_nation
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_nova_nation
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova Nation"
