---
alias: "[Sonos Favourites] Play Nova 96.9"
description: Play Nova 96.9 on Sonos
id: sonos_favourites_play_nova_96_9
trigger:
  - platform: webhook
    webhook_id: sonos_nova_96_9
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_nova_96_9
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Nova 96.9"
