---
alias: "[Sonos Favourites] Play Radio X Chilled"
description: Play Radio X Chilled on Sonos
id: sonos_favourites_play_radio_x_chilled
trigger:
  - platform: webhook
    webhook_id: sonos_radio_x_chilled
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_radio_x_chilled
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Radio X Chilled"
