---
alias: "[Sonos Favourites] Play Radio Hauraki 99.0 (Rock Music)"
description: Play Radio Hauraki 99.0 (Rock Music) on Sonos
id: sonos_favourites_play_radio_hauraki_99_0_rock_music
trigger:
  - platform: webhook
    webhook_id: sonos_radio_hauraki_99_0_rock_music
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_radio_hauraki_99_0_rock_music
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Radio Hauraki 99.0 (Rock Music)"
