---
alias: "[Sonos Favourites] Play triple j (New South Wales)"
description: Play triple j (New South Wales) on Sonos
id: sonos_favourites_play_triple_j_new_south_wales
trigger:
  - platform: webhook
    webhook_id: sonos_triple_j_new_south_wales
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_triple_j_new_south_wales
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "triple j (New South Wales)"
