---
alias: "[Sonos Favourites] Play TripleM 2000s"
description: Play TripleM 2000s on Sonos
id: sonos_favourites_play_triplem_2000s
trigger:
  - platform: webhook
    webhook_id: sonos_triplem_2000s
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_triplem_2000s
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "TripleM 2000s"
