---
alias: "[Sonos Favourites] Play TripleM Soft Rock Digital"
description: Play TripleM Soft Rock Digital on Sonos
id: sonos_favourites_play_triplem_soft_rock_digital
trigger:
  - platform: webhook
    webhook_id: sonos_triplem_soft_rock_digital
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_triplem_soft_rock_digital
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "TripleM Soft Rock Digital"
