---
alias: "[Sonos Favourites] Play Triple J Hottest"
description: Play Triple J Hottest on Sonos
id: sonos_favourites_play_triple_j_hottest
trigger:
  - platform: webhook
    webhook_id: sonos_triple_j_hottest
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_triple_j_hottest
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple J Hottest"
