---
alias: "[Sonos Favourites] Play Triple M 105.1 Melbourne"
description: Play Triple M 105.1 Melbourne on Sonos
id: sonos_favourites_play_triple_m_105_1_melbourne
trigger:
  - platform: webhook
    webhook_id: sonos_triple_m_105_1_melbourne
    allowed_methods:
      - POST
      - PUT
    local_only: true
action:
  - service: script.toggle
    target:
      entity_id: script.sonos_favourites_triple_m_105_1_melbourne
  - service: input_text.set_value
    target:
      entity_id: input_text.sonos_playlist_playing
    data:
      value: "Triple M 105.1 Melbourne"
