---
resource: https://site.web.api.espn.com/apis/v2/sports/rugby-league/3/standings?type=0&level=0
sensor:
  name: scoreboard_nrl
  value_template: "{{ now() }}"
  json_attributes_path: "$['children'][0]['standings']"
  json_attributes:
    - entries
scan_interval: 3600
