---
resource:  https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.champions/standings?seasontype=1&type=0&level=3
sensor:
  name: scoreboard_ucl
  value_template: "{{ now() }}"
  json_attributes_path: "$.[0]['standings']"
  json_attributes:
   - entries
scan_interval: 3600
