---
resource: https://site.web.api.espn.com/apis/v2/sports/baseball/mlb/standings?seasontype=3&type=0&level=3
sensor:
  name: scoreboard_mlb_postseason
  value_template: "{{ now() }}"
  json_attributes:
    - children
scan_interval: 3600
