---
resource: https://site.web.api.espn.com/apis/v2/sports/racing/irl/standings?seasontype=1&type=0&level=3
sensor:
  name: scoreboard_indycar
  value_template: "{{ now() }}"
  json_attributes_path: "$['children'][0]['standings']"
  json_attributes:
    - entries
scan_interval: 3600
