---
id: "pyscript_getdata_hazardwatch"
alias: "PyScript, GetData: Hazard Watch"
description: "PyScript, GetData: Hazard Watch"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
condition: []
mode: single
action:
  - service: pyscript.getdata_hazardwatch
