---
id: "pyscript_getdata_yourspotify"
alias: "PyScript, GetData: Your Spotify"
description: "PyScript, GetData: Your Spotify"
mode: restart
max_exceeded: warning
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: state
    entity_id: input_boolean.ha_startup_pending
    to: "off"

  - platform: time_pattern
    minutes: "/5"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 240

  - service: pyscript.getdata_yourspotify
    data: {}
