---
id: "pyscript_getdata_untappd"
alias: "[PyScript] GetData: Untappd"
description: "[PyScript] GetData: Untappd"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/3"
condition:
  - condition: state
    entity_id: input_boolean.ha_startup_pending
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: pyscript.getdata_untappd_project52
mode: single
