---
id: "pyscript_getdata_essentialenergy"
alias: "PyScript, GetData: Essential Energy Outages"
description: "PyScript, GetData: Essential Energy Outages"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: state
    entity_id: input_boolean.ha_startup_pending
    to: "off"

  - platform: time_pattern
    minutes: "/15"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 240

  - service: pyscript.getdata_essentialenergyoutages
    data:
      entity_id: sensor.essential_energy_outages_current
      dataseturl: https://www.essentialenergy.com.au/Assets/kmz/current.kml
      friendly_name: "[Essential Energy] Outages, Current"
      icon: mdi:alert-circle

  - service: pyscript.getdata_essentialenergyoutages
    data:
      entity_id: sensor.essential_energy_outages_future
      dataseturl: https://www.essentialenergy.com.au/Assets/kmz/future.kml
      friendly_name: "[Essential Energy] Outages, Future"
      icon: mdi:alert-box

  - service: pyscript.getdata_essentialenergyoutages
    data:
      entity_id: sensor.essential_energy_outages_cancelled
      dataseturl: https://www.essentialenergy.com.au/Assets/kmz/cancelled.kml
      friendly_name: "[Essential Energy] Outages, Cancelled"
      icon: mdi:alert-circle-check
