---
id: "pyscript_getdata_yourspotify"
alias: "PyScript, GetData: Your Spotify"
description: "PyScript, GetData: Your Spotify"
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: "5"
condition:
  - condition: state
    entity_id: input_boolean.ha_startup_pending
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
mode: single
action:
  - service: pyscript.getdata_yourspotify
    data: {}
