---
type: custom:stack-in-card
cards:
  - type: custom:mushroom-template-card
    primary: Solar Generation Stats
    icon: mdi:solar-panel
    icon_color: "yellow"
    card_mod:
      style:
        mushroom-state-info$: |
          .container {
           --primary-text-color: #6eaadc;
          }
          .primary {
            font-size: 15px !important;
            filter: drop-shadow(0px 2px 2px rgba(0,0,0,0.5));
          }
        .: |
          ha-card {
            box-shadow: none !important;
            #margin: -10px;
          }
          ha-state-icon {
            filter: drop-shadow(0px 2px 2px rgba(0,0,0,0.5));
            '--mdc-icon-size': 2px !important;
          }
  - type: entities
    card_mod:
      style: |
        ha-card {
          margin-top: -10px;
        }
    entities:
      - square: false
        type: custom:hui-element
        card_type: grid
        columns: 2
        card_mod:
          style:
            .: |
              ha-card {
                background-color: var(--card-background-color);
                padding: 20px;
                box-shadow: none;
              }
        cards:
          - entity: sensor.solar_generation_daily
            name: Daily
            type: custom:mushroom-entity-card
            icon: mdi:solar-panel
            icon_color: "yellow"
            card_mod:
              style:
                .: |
                  ha-card {
                    background-color: var(--background-color);
                    --icon-size: 40px;
                    --icon-symbol-size: 30px;
                    --card-secondary-font-size: 10px;
                    --card-primary-font-size: 12px;
                    padding-top: 5px !important;
                    padding-bottom: 5px !important;
                  }
          - entity: sensor.solar_generation_weekly
            name: Week
            type: custom:mushroom-entity-card
            icon: mdi:solar-panel
            icon_color: "yellow"
            card_mod:
              style:
                .: |
                  ha-card {
                    background-color: var(--background-color);
                    --icon-size: 40px;
                    --icon-symbol-size: 30px;
                    --card-secondary-font-size: 10px;
                    --card-primary-font-size: 12px;
                    padding-top: 5px !important;
                    padding-bottom: 5px !important;
                  }
          - entity: sensor.solar_generation_monthly
            name: Monthly
            type: custom:mushroom-entity-card
            icon: mdi:solar-panel
            icon_color: "yellow"
            card_mod:
              style:
                .: |
                  ha-card {
                    background-color: var(--background-color);
                    --icon-size: 40px;
                    --icon-symbol-size: 30px;
                    --card-secondary-font-size: 10px;
                    --card-primary-font-size: 12px;
                    padding-top: 5px !important;
                    padding-bottom: 5px !important;
                  }
          - entity: sensor.solar_generation_yearly
            name: Yearly
            type: custom:mushroom-entity-card
            icon: mdi:solar-panel
            icon_color: "yellow"
            card_mod:
              style:
                .: |
                  ha-card {
                    background-color: var(--background-color);
                    --icon-size: 40px;
                    --icon-symbol-size: 30px;
                    --card-secondary-font-size: 10px;
                    --card-primary-font-size: 12px;
                    padding-top: 5px !important;
                    padding-bottom: 5px !important;
                  }
