---
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Solar Generation Stats
    icon: mdi:solar-panel
    styles: |-
      .bubble-line {
        background: var(--ha-card-background);
        opacity: 1;
        }

  - square: false
    type: grid
    columns: 2
    cards:
      - entity: sensor.solar_generation_daily
        name: Daily
        type: custom:mushroom-entity-card
        icon: mdi:solar-panel
        icon_color: "yellow"
        card_mod:
          style:
            .: |
              ha-card {
                # background-color: var(--background-color);
                --icon-size: 40px;
                --icon-symbol-size: 30px;
                --card-secondary-font-size: 10px;
                --card-primary-font-size: 12px;
                padding-top: 5px !important;
                padding-bottom: 5px !important;
              }
      - entity: sensor.solar_generation_weekly
        name: Week
        type: custom:mushroom-entity-card
        icon: mdi:solar-panel
        icon_color: "yellow"
        card_mod:
          style:
            .: |
              ha-card {
                # background-color: var(--background-color);
                --icon-size: 40px;
                --icon-symbol-size: 30px;
                --card-secondary-font-size: 10px;
                --card-primary-font-size: 12px;
                padding-top: 5px !important;
                padding-bottom: 5px !important;
              }
      - entity: sensor.solar_generation_monthly
        name: Monthly
        type: custom:mushroom-entity-card
        icon: mdi:solar-panel
        icon_color: "yellow"
        card_mod:
          style:
            .: |
              ha-card {
                # background-color: var(--background-color);
                --icon-size: 40px;
                --icon-symbol-size: 30px;
                --card-secondary-font-size: 10px;
                --card-primary-font-size: 12px;
                padding-top: 5px !important;
                padding-bottom: 5px !important;
              }
      - entity: sensor.solar_generation_yearly
        name: Yearly
        type: custom:mushroom-entity-card
        icon: mdi:solar-panel
        icon_color: "yellow"
        card_mod:
          style:
            .: |
              ha-card {
                # background-color: var(--background-color);
                --icon-size: 40px;
                --icon-symbol-size: 30px;
                --card-secondary-font-size: 10px;
                --card-primary-font-size: 12px;
                padding-top: 5px !important;
                padding-bottom: 5px !important;
              }
