---
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Solar Generation Stats
    icon: mdi:solar-panel
    styles: |-
      .bubble-line {
        background: var(--ha-card-background);
        opacity: 1;
        }
  - square: false
    type: grid
    columns: 2
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: sensor.solar_generation_daily
        name: Daily
        icon: mdi:solar-panel
        sub_button:
          - show_name: false
            show_icon: false
            show_state: true
            show_background: false
            icon: mdi:clock
        button_type: state
        scrolling_effect: false
        show_state: false
        card_layout: normal
        styles: |-
          .bubble-icon {
            color: yellow !important;
          }
          .bubble-button-card-container {
            background: rgba(255, 235, 59,0.25) !important;
          }
      - type: custom:bubble-card
        card_type: button
        entity: sensor.solar_generation_weekly
        name: Weekly
        icon: mdi:solar-panel
        sub_button:
          - show_name: false
            show_icon: false
            show_state: true
            show_background: false
            icon: mdi:clock
        button_type: state
        scrolling_effect: false
        show_state: false
        card_layout: normal
        styles: |-
          .bubble-icon {
            color: yellow !important;
          }
          .bubble-button-card-container {
            background: rgba(255, 235, 59,0.25) !important;
          }
      - type: custom:bubble-card
        card_type: button
        entity: sensor.solar_generation_monthly
        name: Monthly
        icon: mdi:solar-panel
        sub_button:
          - show_name: false
            show_icon: false
            show_state: true
            show_background: false
            icon: mdi:clock
        button_type: state
        scrolling_effect: false
        show_state: false
        card_layout: normal
        styles: |-
          .bubble-icon {
            color: yellow !important;
          }
          .bubble-button-card-container {
            background: rgba(255, 235, 59,0.25) !important;
          }
      - type: custom:bubble-card
        card_type: button
        entity: sensor.solar_generation_yearly
        name: Yearly
        icon: mdi:solar-panel
        sub_button:
          - show_name: false
            show_icon: false
            show_state: true
            show_background: false
            icon: mdi:clock
        button_type: state
        scrolling_effect: false
        show_state: false
        card_layout: normal
        styles: |-
          .bubble-icon {
            color: yellow !important;
          }
          .bubble-button-card-container {
            background: rgba(255, 235, 59,0.25) !important;
          }
