---
alias: "[Zigbee2MQTT] Disable Z2M Join"
id: z2m_disable_join
trigger:
  platform: state
  entity_id: input_boolean.z2m_permit_join
  to : 'off'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: timer.cancel
    data:
      entity_id: timer.z2m_permit_join
