---
id: ha_autogroup_bulk
alias: "[HA] Autogroup - Bulk"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: state
    entity_id: input_boolean.ha_startup_pending
    to: "off"

  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload

  - platform: time_pattern
    minutes: "/15"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 240

  - service: group.set
    data_template:
      object_id: battery_devices
      name: "[Group] Battery Devices"
      icon: mdi:battery
      entities: >-
        {%-
          for state in states.sensor
            if is_state_attr(state.entity_id, 'device_class', 'battery') and
            (state.entity_id.endswith("_battery") or state.entity_id.endswith("_power"))
        %}
        {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
        {%- endfor %}

  - service: group.set
    data_template:
      object_id: media_players
      name: "[Group] Media Players"
      icon: mdi:media-network
      entities: >-
        {{ states.media_player|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: lights
      name: "[Group] Lights"
      icon: mdi:lamps
      entities: >
        {{ states.light|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: automations
      name: "[Group] Automations"
      icon: mdi:home-automation
      entities: >-
        {{ states.automation|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: remotes
      name: "[Group] Remotes"
      icon: mdi:remote
      entities: >-
        {{ states.remote|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: scripts
      name: "[Group] Scripts"
      icon: mdi:script
      entities: >-
        {{ states.script|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: switches
      name: "[Group] Switches"
      icon: mdi:script
      entities: >-
        {{ states.switch|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: calendars
      name: "[Group] Calendars"
      icon: mdi:calendar
      entities: >-
        {{ states.calendar|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: calendars_sport
      name: "[Group] Calendars (Sport)"
      icon: mdi:calendar
      entities: >-
        {{ states.calendar
          |selectattr('entity_id','search','calendar.ical_*')
          |rejectattr('entity_id','search','home_assistant*')
          |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: geo_location
      name: "[Group] Geo Locations"
      icon: mdi:map-marker-alert
      entities: >-
        {{ states.geo_location|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: weather
      name: "[Group] Weather"
      icon: mdi:weather-cloudy-clock
      entities: >-
        {{ states.weather|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: people
      name: "[Group] People"
      icon: mdi:account-group
      entities: >-
        {{ states.person|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data_template:
      object_id: cameras
      name: "[Group] Cameras"
      icon: mdi:cctv
      entities: >-
        {{ states.camera|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: alert_controls
      name: "[Group] Alert Controls"
      icon: mdi:alert-decagram
      entities: >
        {{ states
            |selectattr('entity_id','search','input_boolean.alerts_*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: alert_monitors
      name: "[Group] Alert Monitors"
      icon: mdi:alert-decagram
      entities: >
        {{ states
            |selectattr('entity_id','search','binary_sensor.alerts_*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: alerts
      name: "[Group] Alerts"
      icon: mdi:alert-decagram
      entities: >
        {{ states.alert
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: connectivity_monitors
      name: "[Group] Connectivity Monitors"
      icon: mdi:connection
      entities: >
        {{ states
            |selectattr('entity_id','search','binary_sensor.connected_*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: people
      name: "[Group] People"
      icon: mdi:account-multiple
      entities: >
        {{ states.person|map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: waqi
      name: "[Group] WAQI"
      icon: mdi:smog
      entities: >
        {{ states
          |selectattr('entity_id','search','waqi*')
          |rejectattr('entity_id','search','alert*')
          |rejectattr('entity_id','search','group*')
          |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: docker_pi4srv_containers
      name: "[Group] Docker Pi4Srv Containers"
      icon: mdi:docker
      entities: >
        {{states.sensor
              |selectattr('entity_id','search','sensor.pi4srv_monitordocker_')
              |rejectattr('entity_id','search','_1cpu')
              |rejectattr('entity_id','search','_containers_')
              |rejectattr('entity_id','search','_cpu')
              |rejectattr('entity_id','search','_images')
              |rejectattr('entity_id','search','_memory')
              |rejectattr('entity_id','search','_version')
              |map(attribute='entity_id')
              |list|sort }}
  - service: group.set
    data:
      object_id: docker_pi4srv_switches
      name: "[Group] Docker Pi4Srv Switches"
      icon: mdi:docker
      entities: >
        {{states.switch
              |selectattr('entity_id','search','pi4srv_monitordocker_')
              |map(attribute='entity_id')
              |list|sort }}

  - service: group.set
    data:
      object_id: docker_tbsh1_containers
      name: "[Group] Docker tbsh1 Containers"
      icon: mdi:docker
      entities: >
        {{states.sensor
              |selectattr('entity_id','search','sensor.tbsh1_monitordocker_')
              |rejectattr('entity_id','search','_1cpu')
              |rejectattr('entity_id','search','_containers_')
              |rejectattr('entity_id','search','_cpu')
              |rejectattr('entity_id','search','_images')
              |rejectattr('entity_id','search','_memory')
              |rejectattr('entity_id','search','_version')
              |map(attribute='entity_id')
              |list|sort }}
  - service: group.set
    data:
      object_id: docker_tbsh1_switches
      name: "[Group] Docker tbsh1 Switches"
      icon: mdi:docker
      entities: >
        {{states.switch
              |selectattr('entity_id','search','tbsh1_monitordocker_')
              |map(attribute='entity_id')
              |list|sort }}

  - service: group.set
    data:
      object_id: docker_tbsh2_containers
      name: "[Group] Docker tbsh2 Containers"
      icon: mdi:docker
      entities: >
        {{states.sensor
              |selectattr('entity_id','search','sensor.tbsh2_monitordocker_')
              |rejectattr('entity_id','search','_1cpu')
              |rejectattr('entity_id','search','_containers_')
              |rejectattr('entity_id','search','_cpu')
              |rejectattr('entity_id','search','_images')
              |rejectattr('entity_id','search','_memory')
              |rejectattr('entity_id','search','_version')
              |map(attribute='entity_id')
              |list|sort }}
  - service: group.set
    data:
      object_id: docker_tbsh2_switches
      name: "[Group] Docker tbsh2 Switches"
      icon: mdi:docker
      entities: >
        {{states.switch
              |selectattr('entity_id','search','tbsh2_monitordocker_')
              |map(attribute='entity_id')
              |list|sort }}

  - service: group.set
    data:
      object_id: docker_tbsh3_containers
      name: "[Group] Docker tbsh3 Containers"
      icon: mdi:docker
      entities: >
        {{states.sensor
              |selectattr('entity_id','search','sensor.tbsh3_monitordocker_')
              |rejectattr('entity_id','search','_1cpu')
              |rejectattr('entity_id','search','_containers_')
              |rejectattr('entity_id','search','_cpu')
              |rejectattr('entity_id','search','_images')
              |rejectattr('entity_id','search','_memory')
              |rejectattr('entity_id','search','_version')
              |map(attribute='entity_id')
              |list|sort }}
  - service: group.set
    data:
      object_id: docker_tbsh3_switches
      name: "[Group] Docker tbsh3 Switches"
      icon: mdi:docker
      entities: >
        {{states.switch
              |selectattr('entity_id','search','tbsh3_monitordocker_')
              |map(attribute='entity_id')
              |list|sort }}

  - service: group.set
    data:
      object_id: docker_tbsh5_containers
      name: "[Group] Docker tbsh5 Containers"
      icon: mdi:docker
      entities: >
        {{states.sensor
              |selectattr('entity_id','search','sensor.tbsh5_monitordocker_')
              |rejectattr('entity_id','search','_1cpu')
              |rejectattr('entity_id','search','_containers_')
              |rejectattr('entity_id','search','_cpu')
              |rejectattr('entity_id','search','_images')
              |rejectattr('entity_id','search','_memory')
              |rejectattr('entity_id','search','_version')
              |map(attribute='entity_id')
              |list|sort }}
  - service: group.set
    data:
      object_id: docker_tbsh5_switches
      name: "[Group] Docker tbsh5 Switches"
      icon: mdi:docker
      entities: >
        {{states.switch
              |selectattr('entity_id','search','tbsh5_monitordocker_')
              |map(attribute='entity_id')
              |list|sort }}

  - service: group.set
    data:
      object_id: updates_homeassistant
      name: "[Updates] Home Assistant"
      icon: mdi:home-assistant
      entities: >
        {{expand(integration_entities('Supervisor'))
          |selectattr('domain', 'eq', 'update')
          |map(attribute='entity_id')
          |list|sort }}
  - service: group.set
    data:
      object_id: updates_hacs
      name: "[Updates] HA Community Store"
      icon: mdi:home-assistant
      entities: >
        {{expand(integration_entities('hacs'))
          |selectattr('domain', 'eq', 'update')
          |map(attribute='entity_id')
          |list|sort }}
  - service: group.set
    data:
      object_id: updates_docker
      name: "[Updates] Docker"
      icon: mdi:docker
      entities: >
        {{states.update
          |selectattr('entity_id', 'search', 'wud')
          |map(attribute='entity_id')
          |list|sort }}
  - service: group.set
    data:
      object_id: updates_unifi
      name: "[Updates] Unifi"
      icon: si:ubiquiti
      entities: >
        {{expand(integration_entities('unifi'))
          |selectattr('domain', 'eq', 'update')
          |map(attribute='entity_id')
          |list|sort }}
  - service: group.set
    data:
      object_id: updates_zigbee2mqtt
      name: "[Updates] Zigbee2MQTT"
      icon: mdi:zigbee
      entities: >
        {{states.update
          |selectattr('entity_id', 'search', 'z2m')
          |map(attribute='entity_id')
          |list|sort }}
  - service: group.set
    data:
      object_id: updates_other
      name: "[Updates] Other"
      icon: mdi:update
      entities: >
        {{states.update
          |rejectattr('entity_id', 'search', 'wud')
          |rejectattr('entity_id', 'search', 'z2m')
          |rejectattr('entity_id', 'in', expand(integration_entities('hacs'))|map(attribute='entity_id')|list)
          |rejectattr('entity_id', 'in', expand(integration_entities('Supervisor'))|map(attribute='entity_id')|list)
          |rejectattr('entity_id', 'in', expand(integration_entities('unifi'))|map(attribute='entity_id')|list)
          |map(attribute='entity_id')
          |list|sort }}

  - service: group.set
    data:
      object_id: qbittorrent
      name: "[Group] qbittorrent"
      icon: mdi:download-box
      entities: >
        {{ states
          |selectattr('entity_id','search','qbittorrent_')
          |map(attribute='entity_id')
          |list|sort }}

  - service: group.set
    data:
      object_id: rssfeeds
      name: "[Group] RSS Feeds"
      icon: mdi:rss-box
      entities: >
        {{ states
          |selectattr('entity_id','search','rssfeed_')
          |map(attribute='entity_id')
          |list|sort }}

  - service: group.set
    data:
      object_id: addon_switch
      name: "[Group] Add-on Switches"
      icon: mdi:toggle-switch
      entities: >
        {{ states
            |selectattr('entity_id','search','switch.addon_*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: upcomingsport_withevents
      name: "[Group] Upcoming Sport, With Events"
      icon: mdi:soccer
      entities: >
        {{ states|selectattr('entity_id','search','sensor.upcoming_sport_')
                |rejectattr('entity_id','search','this_week')
                |rejectattr('entity_id','search','next_24_hours')
                |rejectattr('attributes.remaining_events','eq',0)
                |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: upcomingsport_withoutevents
      name: "[Group] Upcoming Sport, Without Events"
      icon: mdi:soccer
      entities: >
        {{ states|selectattr('entity_id','search','sensor.upcoming_sport_')
                |rejectattr('entity_id','search','this_week')
                |rejectattr('entity_id','search','next_24_hours')
                |selectattr('attributes.remaining_events','eq',0)
                |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: upcomingsport_thisweek
      name: "[Group] Upcoming Sport, This Week"
      icon: mdi:soccer
      entities: >
        {{ states|selectattr('entity_id','search','sensor.upcoming_sport_')
                |rejectattr('entity_id','search','this_week')
                |rejectattr('entity_id','search','next_24_hours')
                |rejectattr('attributes.remaining_events','==',0)
                |selectattr("attributes.nextevent_timeto", 'defined')
                |selectattr('attributes.nextevent_timeto','<=',7)
                |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: livetrafficnsw
      name: "[Group] Live Traffic NSW"
      icon: mdi:dump-truck
      entities: >
        {{ states|selectattr('entity_id','search','sensor.getdata_livetrafficnsw_')
                |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: automations_sonos_favourites
      name: "[Group] Automations, Sonos Favourites"
      icon: si:sonos
      entities: >
        {{ states
            |selectattr('entity_id','search','automation.sonos_favourites*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: script_sonos_playlists
      name: "[Group] Scripts, Sonos Playlists"
      icon: si:sonos
      entities: >
        {{ states
            |selectattr('entity_id','search','script.sonos_favourites*')
            |map(attribute='entity_id')|list|sort }}

  - service: group.set
    data:
      object_id: hibp_breaches
      name: "[Group] Have I Been Pwned (HIBP) Breach Data"
      icon: mdi:virus-outline
      entities: >
        {{ states
            |selectattr('entity_id','search','sensor.breaches_*')
            |map(attribute='entity_id')|list|sort }}
