---
id: ha_autogroup_tvguide
alias: "[HA] Autogroup - TV Guide"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: state
    entity_id: input_boolean.ha_startup_pending
    to: "off"

  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: reload

  - platform: time_pattern
    hours: "/1"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 240

  - service: group.set
    data:
      object_id: tvguide_fta
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'FTA')
            | map(attribute='entity_id') | list | sort }}

  - service: group.set
    data:
      object_id: tvguide_foxtel_news
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'Foxtel News')
            | map(attribute='entity_id') | list | sort }}

  - service: group.set
    data:
      object_id: tvguide_foxtel_sport
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'Foxtel Sport')
            | map(attribute='entity_id') | list | sort }}

  - service: group.set
    data:
      object_id: tvguide_optus_sport
      entities: |
        {% set l1 =  states
            |selectattr('entity_id','search','sensor.tvguide_optussport*')
            |map(attribute='entity_id')|list|sort %}
        {% set l2 = states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'Optus')
            | map(attribute='entity_id') | list | sort %}
        {{ l1 + l2 | sort }}

  - service: group.set
    data:
      object_id: tvguide_uk
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'UK')
            | map(attribute='entity_id') | list | sort }}

  - service: group.set
    data:
      object_id: tvguide_uk_sport
      entities: |
        {% set l1 =  states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'UK')
            |selectattr('entity_id','search','sensor.tvguide_eurosport*')
            | map(attribute='entity_id') | list | sort %}
        {% set l2 = states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'UK')
            |selectattr('entity_id','search','sensor.tvguide_sky_sports*')
            | map(attribute='entity_id') | list | sort %}
        {% set l3 = states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'UK')
            |selectattr('entity_id','search','sensor.tvguide_tnt*')
            | map(attribute='entity_id') | list | sort %}
        {{ l1 + l2 + l3 | sort }}

  - service: group.set
    data:
      object_id: tvguide_uk_radio
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'UKRadio')
            | map(attribute='entity_id') | list | sort }}

  - service: group.set
    data:
      object_id: tvguide_us
      entities: >
        {{ states
            | selectattr('attributes.category', 'defined')
            | selectattr('attributes.category', 'eq', 'tvguide')
            | selectattr('attributes.channel_group', 'eq', 'US')
            | map(attribute='entity_id') | list | sort }}
