---
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Untappd Settings and Controls
    icon: mdi:beer-outline
    styles: |-
      .bubble-line {
        background: var(--ha-card-background);
        opacity: 1;
        }
  - type: entities
    show_header_toggle: false
    state_color: true
    card_mod:
      style: |
        #states > * {
          margin: 0 !important;
        }
    entities:
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: automation.*untappd*
              options:
                secondary_info: last-triggered
        sort:
          method: friendly_name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          padding: 5
          card_mod:
            style: |
              #measure {
                padding-top: 0 !important;
              }
              #measure > * {
                margin: 0 !important;
              }
          head:
            type: custom:template-entity-row
            name: Untappd Automations
            icon: mdi:sync-alert
            state: ""
