---
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Weather Settings and Controls
    icon: mdi:weather-partly-rainy
    styles: |-
      .bubble-line {
        background: var(--ha-card-background);
        opacity: 1;
        }
  - type: entities
    show_header_toggle: false
    state_color: true
    card_mod:
      style: |
        #states > * {
          margin: 0 !important;
        }
    entities:
      - entity: input_boolean.alerts_weather
        name: Alert Notifications
      - type: section
      - type: custom:auto-entities
        filter:
          include:
            - entity_id: automation.weather_*
            - entity_id: automation.openuv_*
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          padding: 5
          head:
            type: custom:template-entity-row
            name: Weather Automations
            icon: mdi:sync-alert
            state: ""
      - type: custom:auto-entities
        filter:
          include:
            - domain: alert
              attributes:
                category: weather
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          card_mod:
            style: |
              #measure > * {
                margin: 0 !important;
              }
          head:
            type: custom:template-entity-row
            name: Weather Alerts
            icon: mdi:alert-circle
            state: ""
      - type: custom:auto-entities
        filter:
          include:
            - domain: binary_sensor
              attributes:
                category: weather_alert
        sort:
          method: name
          ignore_case: true
        card:
          type: custom:fold-entity-row
          card_mod:
            style: |
              #measure > * {
                margin: 0 !important;
              }
          head:
            type: custom:template-entity-row
            name: Weather Alert Sensors
            icon: mdi:alert-circle
            state: ""
      - type: custom:fold-entity-row
        card_mod:
          style: |
            #measure > * {
              margin: 0 !important;
            }
        head:
          type: custom:template-entity-row
          name: Weather HA Integrations Connected
          icon: mdi:weather-partly-snowy-rainy
          state: ""
        entities:
          - entity: binary_sensor.ha_connected_integration_bureau_of_meteorology
          - entity: binary_sensor.ha_connected_integration_pirateweather
          - entity: binary_sensor.ha_connected_integration_openuv
          - entity: binary_sensor.ha_connected_integration_waqi
          - entity: binary_sensor.ha_connected_integration_weatherflow_cloud
          - entity: binary_sensor.ha_connected_integration_weatherflow_local
      - type: custom:fold-entity-row
        card_mod:
          style: |
            #measure > * {
              margin: 0 !important;
            }
        head:
          type: custom:template-entity-row
          name: Weather Alert Thresholds
          icon: mdi:thermometer-lines
          state: ""
        padding: 5
        entities:
          - type: custom:numberbox-card
            entity: input_number.low_temperature_threshold
          - type: custom:numberbox-card
            entity: input_number.high_temperature_threshold
