---
id: clear_alert
alias: "[Notifications] Clear Alert"
mode: parallel
max: 25
trigger:
  - platform: state
    id: mobile
    entity_id:
      - alert.weatherflow_cloud
      - alert.weatherflow_local
      - alert.zigbee_network
      - alert.test_alert
    to:
      - "off"
      - "idle"
action:
  - service: automation.turn_off
    target:
      entity_id: automation.notifications_mobile_notification_cleared
    data:
      stop_actions: false

  - service: notify.alert
    data:
      message: clear_notification
      data:
        tag: "{{ trigger.entity_id.split('.')[1] }}"
    continue_on_error: true

  - if: "{{ trigger.id == 'alert' }}"
    then:
      - service: persistent_notification.dismiss
        data:
          notification_id: "{{ trigger.entity_id.split('.')[1] }}"
        continue_on_error: true

  - service: automation.turn_on
    target:
      entity_id: automation.notifications_mobile_notification_cleared
