---
alias: "[Notification] Lightning Warning"
id: notification_lightning_warning
mode: single

trigger:
  - platform: state
    entity_id: sensor.weather_lightning_count

condition:
  - condition: numeric_state
    entity_id: sensor.weather_lightning_distance
    below: 10

action:
  - service: notify.alert
    data:
      title: Weather Alert
      message: Lightning within 10km of home!
      data:
        tag: "weather-lightning"
        subtitle: "⚡️ Lightning within 10km ⚡"
