---
alias: "[Notifications] Offline Integrations"
id: notifications_offline_integrations
mode: single
trigger:
  - platform: time_pattern
    minutes: "/1" # Check every 1 minute
condition:
  - condition: template
    value_template: >
      {{ expand('group.connectivity_monitors')
          | rejectattr('entity_id', 'in', ['binary_sensor.ha_connected_integration_offline_integrations'])
          | selectattr('state', 'eq', 'off')
          | list
          | count > 0 }}
action:
  - variables:
      current_count: >
        {{ expand('group.connectivity_monitors')
            | rejectattr('entity_id', 'in', ['binary_sensor.ha_connected_integration_offline_integrations'])
            | selectattr('state', 'eq', 'off')
            | list
            | count }}
      previous_count: >
        {{ states('input_number.offline_integration_count') | int }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_count != previous_count }}"
        sequence:
          - service: notify.alert
            data:
              title: Offline Integrations Detected
              message: >-
                {{ current_count }} Offline Integrations Detected:
                {{ expand('group.connectivity_monitors')
                      | rejectattr('entity_id', 'in', ['binary_sensor.ha_connected_integration_offline_integrations'])
                      | selectattr('state', 'eq', 'off')
                      | map(attribute='entity_id')
                      | map('replace', 'binary_sensor.ha_connected_integration_', '')
                      | list
                      | sort
                      | join('\n- ') }}
              data:
                tag: offline_integrations
                notification_id: offline_integrations
                push:
                  badge: 1
                  sound: none
                  interruption-level: time-sensitive
                presentation_options:
                  - alert
                  - badge
                group: alerts
                actions:
                  - title: "Restart HA"
                    action: notify_action_restart_ha
                    destructive: true
                    authenticationRequired: true
                  - title: "Pause Alert"
                    action: pause_alert_offline_integrations

          - service: input_number.set_value
            data:
              entity_id: input_number.offline_integration_count
              value: "{{ current_count }}"
