---
id: unavailable_entities_notification
alias: "[Notifications] Unavailable Entities"
description: "Create persistent notification if there are unavailable entities, dismiss if none."
mode: restart
trigger:
  - platform: state
    entity_id: sensor.unavailable_entities
    to: ~
condition:
  - condition: template
    value_template: >
      {{ is_number(trigger.from_state.state)
          and is_number(trigger.to_state.state) }}
action:
  - choose:
      conditions:
        - condition: numeric_state
          entity_id: sensor.unavailable_entities
          below: 1
      sequence:
        - service: persistent_notification.dismiss
          data:
            notification_id: unavailable_entities
    default:
      - service: persistent_notification.create
        data:
          title: "Unavailable Entities"
          message: >
            - {{ expand(state_attr('sensor.unavailable_entities','entity_id'))
                  |map(attribute='entity_id')|join('\n- ') }}
          notification_id: unavailable_entities
