---
id: "1705097473383"
alias: "[GTFS] Get New Data and Run Update"
description: ""
trigger:
  - platform: time
    at: 02:30:00
    enabled: true
condition:
  - condition: time
    weekday:
      - wed
    enabled: true
action:
  - service: shell_command.gtfs_get_nenw_buses
    metadata: {}
    data: {}
  - service: shell_command.gtfs_get_trains
    metadata: {}
    data: {}
  - service: shell_command.gtfs_get_tfnsw
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: gtfs2.update_gtfs
    metadata: {}
    data:
      extract_from: zip
      url: na
      file: buses_nenw
      clean_feed_info: true
  - service: gtfs2.update_gtfs
    metadata: {}
    data:
      extract_from: zip
      url: na
      file: nswtrains
      clean_feed_info: true
  - service: gtfs2.update_gtfs
    metadata: {}
    data:
      extract_from: zip
      url: na
      file: tfnsw
      clean_feed_info: true
mode: single
