---
id: "1705097473383"
alias: "[GTFS] Get New Data and Run Update"
description: ""
trigger:
  - platform: time
    at: 02:30:00
    enabled: true
condition:
  - condition: time
    weekday:
      - wed
    enabled: true
action:
  - service: pyscript.download_gtfs
    data:
      url: https://api.transport.nsw.gov.au/v1/gtfs/schedule/regionbuses/newenglandnorthwest
      filename: buses_nenw.zip

  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0

  - service: pyscript.download_gtfs
    data:
      url: https://api.transport.nsw.gov.au/v1/gtfs/schedule/nswtrains
      filename: nswtrains.zip

  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0

  # - service: pyscript.download_gtfs
  #   data:
  #     url: https://api.transport.nsw.gov.au/v1/publictransport/timetables/complete/gtfs
  #     filename: tfnsw.zip

  # - delay:
  #     hours: 0
  #     minutes: 5
  #     seconds: 0
  #     milliseconds: 0

  - service: gtfs2.update_gtfs
    metadata: {}
    data:
      extract_from: zip
      url: na
      file: buses_nenw
      clean_feed_info: true
      api_key_location: not_applicable
      api_key_name: x
      check_source_dates: false
      api_key: x

  - service: gtfs2.update_gtfs
    metadata: {}
    data:
      extract_from: zip
      url: na
      file: nswtrains
      clean_feed_info: true
      api_key_location: not_applicable
      api_key_name: x
      check_source_dates: false
      api_key: x

  # - service: gtfs2.update_gtfs
  #   metadata: {}
  #   data:
  #     extract_from: zip
  #     url: na
  #     file: tfnsw
  #     clean_feed_info: true
  #     api_key_location: not_applicable
  #     api_key_name: x
  #     check_source_dates: false
  #     api_key: x

mode: single
