---
id: "influx2entity_flighttrack365day"
alias: "InfluxDB to Entity: 365 Day Flight Tracker"
description: "InfluxDB to Entity: 365 Day Flight Tracker"
mode: restart
max_exceeded: warning
trigger:
  - platform: homeassistant
    id: startup
    event: start

  - platform: state
    entity_id: input_boolean.ha_startup_pending
    to: "off"

  - platform: time_pattern
    hours: "/1"

action:
  - if: "{{ trigger.id == 'startup' }}"
    then:
      - delay: 240

  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "Flights")
          |> filter(fn: (r) => r["entity_id"] == "flighttracker_flights_24hr")
          |> filter(fn: (r) => r["_field"] == "value")
          |> drop(columns: ["friendly_name"])
          |> aggregateWindow(every: 1d, fn: max, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "max")
      entity_id: sensor.archive_flighttracker_flights_365day
      unit_of_measurement: Flights
      friendly_name: Flight Tracker - Flights - 365 Day
      icon: "mdi:airplane-takeoff"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name: "Australia/Sydney")
        from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "m")
          |> filter(fn: (r) => r["entity_id"] == "flighttracker_distance_max")
          |> filter(fn: (r) => r["_field"] == "value")
          |> map(fn: (r) => ({r with _value: r._value / 1000.0}))
          |> aggregateWindow(every: 1d, fn: max, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "max")
      entity_id: sensor.archive_flighttracker_maxdistance_365day
      unit_of_measurement: km
      friendly_name: Flight Tracker - Max Distance - 365 Day
      icon: "mdi:airplane-marker"
  - service: pyscript.influxdb2_query_to_entity
    data:
      query: >-
        import "timezone" option location = timezone.location(name:
        "Australia/Sydney") from(bucket: "homeassistant")
          |> range(start: -1y)
          |> filter(fn: (r) => r["_measurement"] == "m")
          |> filter(fn: (r) => r["entity_id"] == "flighttracker_distance_max")
          |> filter(fn: (r) => r["_field"] == "value")
          |> map(fn: (r) => ({r with _value: r._value / 1000.0}))
          |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)
          |> fill(value: 0.0)
          |> yield(name: "mean")
      entity_id: sensor.archive_flighttracker_avgdistance_365day
      unit_of_measurement: km
      friendly_name: Flight Tracker - Avg Distance - 365 Day
      icon: "mdi:airplane-marker"
