---
alias: "[Solcast] Update During Day"
id: solcast_update
trigger:
  - platform: time_pattern
    hours: /2
condition:
  - condition: state
    entity_id: binary_sensor.connected_wan
    state: "on"
  - condition: sun # only run between sunrise and sunset
    before: sunset
    after: sunrise
action:
  - delay:
      seconds: "{{ range(30, 360)|random|int }}"
  - service: solcast_solar.update_forecasts
    data: {}
mode: single
