---
id: github_stars
alias: Github - Notify when repo starred
trigger:
  - platform: state
    entity_id:
      - sensor.bacco007_homeassistantconfig_stars
condition:
  - condition: template
    value_template: >
      {% set ignore = ['unknown', 'unavailable', 'none','0'] %}
      {{ trigger.from_state.state not in ignore and
        trigger.to_state.state not in ignore and
        trigger.to_state.state != trigger.from_state.state }}
mode: restart
action:
  - service: persistent_notification.create
    data_template:
      title: Github - Repo Star
      notification_id: github_repostar
      message: >-
        "{{ trigger.to_state.attributes.friendly_name | regex_replace(find='bacco007/', replace='', ignorecase=False) }}: {{ trigger.from_state.state }} => {{ trigger.to_state.state }}"
