---
sensor:
  - name: "[Energy] Time of Use Tariff Type"
    unique_id: energy_timeofuse_tariff_type
    state: >
      {#-
      Australian Essential Energy NSW Peak-shoulder-offpeak sensor defined
      https://www.essentialenergy.com.au/-/media/Project/EssentialEnergy/Website/Files/Our-Network/TimeofUseBrochure.pdf
      Peak: 5pm to 8pm Weekdays
      Shoulder: 7am to 5pm + 8pm to 10pm Weekdays
      Off-Peak: 10pm to 7am Weekdays, all weekend (19pm Fri to 7am Mon)
      #}
      {%- if is_state('schedule.energy_timeofuse_tariff_peak', 'on') %}
        Peak
      {%- elif is_state('schedule.energy_timeofuse_tariff_shoulder', 'on') %}
        Shoulder
      {%- elif is_state('schedule.energy_timeofuse_tariff_offpeak', 'on') %}
        Off-Peak
      {%- endif %}
    attributes:
      category: energy

  - name: "[Energy] Time of Use Tariff"
    unique_id: energy_timeofuse_tariff
    device_class: monetary
    state_class: measurement
    icon: mdi:cash-plus
    unit_of_measurement: $/kWh
    state: >
      {%- if states('sensor.energy_timeofuse_tariff_type') in ("Peak") %}
        0.42
      {%- elif states('sensor.energy_timeofuse_tariff_type') in ("Shoulder") %}
        0.4081
      {%- elif states('sensor.energy_timeofuse_tariff_type') in ("Off-Peak") %}
        0.2674
      {%- endif %}
    attributes:
      category: energy

  - name: "[Energy] Solar Feed-In Tariff"
    unique_id: energy_solar_tariff
    device_class: monetary
    state_class: measurement
    icon: mdi:cash-plus
    unit_of_measurement: $/kWh
    state: >
      0.07
    attributes:
      category: energy

  - name: "[Energy] Supply Charge"
    unique_id: energy_supply_charge
    device_class: monetary
    state_class: measurement
    icon: mdi:cash-plus
    unit_of_measurement: $/Day
    state: >
      1.4445
    attributes:
      category: energy
