---
sensor:
  - unique_id: helper_date
    name: "[Helper] Date"
    icon: mdi:calendar-today
    state: >
      {%- set date = states('sensor.date') %}
      {%- set datetime = strptime(date, '%Y-%m-%d') | default('', true)  %}
      {%- set weekday = datetime.strftime('%A') | default('', true) %}
      {%- set month = datetime.strftime('%B') | default('', true) %}
      {%- set day = datetime.strftime('%d') | int %}
      {%-
        set suffix = 'st' if (day % 10 == 1 and day != 11)
        else 'nd' if (day % 10 == 2 and day != 12)
        else 'rd' if (day % 10 == 3 and day != 13)
        else 'th'
      %}
      {{ weekday }}, {{ month }} {{ day }}{{ suffix }}
    attributes:
      date_friendly: >
        {%- set date = states('sensor.date') %}
        {%- set datetime = strptime(date, '%Y-%m-%d') | default('', true) %}
        {%- set month = datetime.strftime('%B') | default('', true) %}
        {%- set day = datetime.strftime('%d') | int %}
        {{ month }} {{ day }}
      date_long: >
        {%- set months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] %}
        {%- set month = months[now().strftime('%m') | int -1] %}
        {%- set days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]  %}
        {%- set day = days[now().strftime('%w') | int] %}
        {%- set daynum = now().strftime('%d') | int %}
        {%-
          set suffix = 'st' if (daynum % 10 == 1 and daynum != 11)
          else 'nd' if (daynum % 10 == 2 and daynum != 12)
          else 'rd' if (daynum % 10 == 3 and daynum != 13)
          else 'th'
        %}
        {{day}}, {{month}} {{daynum}}{{suffix}} {{now().strftime('%Y')}}
      day_phase: >
        {%- if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Morning
        {%- elif states.sun.sun.state == "above_horizon" %}
            Day
        {%- elif now() < now().replace(hour=22).replace(minute=0).replace(second=0) and
            now() > now().replace(hour=9).replace(minute=0).replace(second=0) %}
            Evening
        {%- else %}
            Night
        {%- endif %}
      day_after_tomorrow: >
        {%- set date = states('sensor.date') %}
        {%- set datetime = strptime(date, '%Y-%m-%d') | default('', true) %}
        {%- set timestamp = as_timestamp(datetime) + 2*24*60*60 %}
        {{ timestamp | timestamp_custom('%A') }}
      year: >
        {{ now().strftime("%Y")|int(0) }}
      month: >
        {{ now().strftime("%m")|int(0) }}
      day: >
        {{ now().strftime("%d")|int(0) }}
      dayofyear: >
        {{ now().strftime("%j")|int(0) }}
      daysinmonth: >
        {%- set month = now().strftime("%m")|int(0) %}
        {%- if month in [1,3,5,7,8,10,12] %}
          31
        {%- elif month in [4,6,9,11] %}
          30
        {%- elif month == 2 %}
          {%- set year = now().year %}
          {%- if ((year % 4) == 0 and (year % 100) > 0) or (year % 400) == 0 %}
            29
          {%- else %}
            28
          {%- endif %}
        {%- endif %}
      weekofyear: >
        {{ now().strftime("%W")|int(0) + 1 }}
      weekdaynumber: >
        {%- set days = ["6", "0", "1", "2", "3", "4", "5"] %}
        {%- set day = days[now().strftime('%w')|int(0)] %}
        {{ day }}
      weekdayname_en: >
        {%- set days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %}
        {%- set day = days[state_attr('sensor.helper_date', 'weekdaynumber')|int(0)] %}
        {{ day }}
      monthname_en: >
        {% set months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] %}
        {% set month = months[state_attr('sensor.helper_date', 'month')|int(0)-1] %}
        {{ month }}
      yyyymmdd: >
        {{ now().strftime("%Y") + '/' + now().strftime("%m") + '/' + now().strftime("%d") }}
      yyyyddmm: >
        {{ now().strftime("%Y") + '/' + now().strftime("%d") + '/' + now().strftime("%m") }}
      ddmmyyyy: >
        {{ now().strftime("%d") + '/' + now().strftime("%m") + '/' + now().strftime("%Y") }}
      utc: >
        {% set utc_date = states('sensor.date_time_utc').split(',')[0] %}
        {% set utc_year = utc_date.split('-')[0] %}
        {% set utc_month = utc_date.split('-')[1] %}
        {% set utc_day = utc_date.split('-')[2] %}
        {{ utc_year + "/" + utc_month + "/" + utc_day }}

  - unique_id: helper_time
    name: "[Helper] Time"
    icon: mdi:clock-check
    state: >
      {{ now().strftime("%H")|string + ':' + now().strftime("%M")|string + ':' +now().strftime("%S")|string }}
    attributes:
      hour: >
        {{ now().strftime("%H")|int(0) }}
      minute: >
        {{ now().strftime("%M")|int(0) }}
      second: >
        {{ now().strftime("%S")|int(0) }}
      long: >
        {{ now().strftime("%H")|string + ':' + now().strftime("%M")|string + ':' + now().strftime("%S")|string }}
      short: >
        {{ now().strftime("%H")|string + ':' + now().strftime("%M")|string }}
      internet: >
        {{ states('sensor.swatch_time') }}
      utc: >
        {{ states('sensor.time_utc') }}
      sec_midnight: >
        {{ now().strftime("%H")|int(0)*60*60 + now().strftime("%M")|int(0)*60 + now().strftime("%S")|int(0) }}
      hourmin: >
        {{ now().strftime("%H")|int(0)*100 + now().strftime("%M")|int(0) }}
      dst: >
        {{ now().timetuple().tm_isdst > 0 }}
      time_long: >
        {%- set hour = states('sensor.time').split(':')[0] | int %}
        {%- set minute = states('sensor.time').split(':')[1] | int %}
        {%- set minute_str = '' %}
        {%- if minute == 15 or minute == 45 %}
          {%- set minute_str = 'a quarter' %}
        {%- elif minute == 30 %}
          {%- set minute_str = 'half' %}
        {%- else %}
          {%- if minute > 30 %}
            {%- set minute_str = (60 - minute) | string %}
          {%- elif minute != 0 %}
            {%- set minute_str = minute | string %}
          {%- endif %}
          {%- if minute_str %}
            {%- if minute > 1 %}
              {%- set minute_str = minute_str + ' minutes' %}
            {%- else %}
              {%- set minute_str = minute_str + ' minute' %}
            {%- endif %}
          {%- endif %}
        {%- endif %}
        {%- if minute > 30 %}
          {%- set minute_str = minute_str + ' to' %}
          {%- set hour = hour + 1 %}
          {%- if hour >= 24 %}
            {%- set hour = hour - 24 %}
          {%- endif %}
        {%- elif minute > 0 %}
          {%- set minute_str = minute_str + ' past' %}
        {%- endif %}
        {%- if hour == 0 %}
          {%- set hour_str = 'midnight' %}
        {%- elif hour == 12 %}
          {%- set hour_str = 'noon' %}
        {%- elif hour > 12 %}
          {%- set hour_str = hour - 12 %}
        {%- else %}
          {%- set hour_str = hour %}
        {%- endif %}
        {%- if minute_str %}
          {{ minute_str }} {{ hour_str }}
        {%- elif hour != 0 and hour != 12 %}
          {{ hour_str }} O'Clock
        {%- else %}
          {{ hour_str }}
        {%- endif %}
      time_quarterly: >
        {%- set hour = states('sensor.time').split(':')[0] | int %}
        {%- set minutes = states('sensor.time').split(':')[1] | int %}
        {%- if minutes >= 45 %}
          {%- set minute = '45' %}
        {%- elif minutes >= 30 %}
          {%- set minute = '30' %}
        {%- elif minutes >= 15 %}
          {%- set minute = '15' %}
        {%- else %}
          {%- set minute = '00' %}
        {%- endif %}
        {{ hour }}:{{ minute }}
