---
binary_sensor:
  - name: "UV Risk Alert"
    unique_id: uv_risk_alert
    icon: mdi:weather-sunny-alert
    state: >
      {{ states('sensor.uv_risk_today') in ['Very High','High']
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: openuv
    availability: "{{ has_value('sensor.uv_risk_today') }}"

sensor:
  - name: "UV Risk Today"
    unique_id: uv_risk_today
    icon: mdi:weather-sunny
    state: >
      {% set level = states('sensor.max_uv_index')|int(0) %}
      {% if is_number(level) %}
        {% if level < 3 %} Low
        {% elif level < 5 %} Moderate
        {% elif level < 7 %} Moderate High
        {% elif level < 9 %} High
        {% else %} Very High
        {% endif %}
      {% endif %}
    attributes:
      category: openuv
    availability: "{{ is_number(states('sensor.max_uv_index')) }}"

  - name: "UV Index"
    unique_id: uv_index
    icon: mdi:weather-sunny
    state_class: measurement
    state: "{{ states('sensor.current_uv_index')|float('unknown') }}"
    attributes:
      category: openuv
    availability: "{{ is_number(states('sensor.current_uv_index')) }}"
