---
# trigger:
#   - platform: homeassistant
#     event: start
#   - platform: time_pattern
#     hours: "/6"
#   {%- for s in states
#     | selectattr('entity_id','search','calendar.ical_*')
#     | rejectattr('entity_id', 'search', 'calendar.ical_home_assistant')
#     | rejectattr('entity_id', 'search', 'calendar.ical_test')
#     | list %}
#   - platform: calendar
#     event: end
#     entity_id: {{ s.entity_id }}
#   {%- endfor %}
#   - platform: event
#     event_type: event_template_reloaded
# action:
#   - service: calendar.get_events
#     data:
#       duration:
#         hours: 24
#     response_variable: agenda
#     target:
#       entity_id:
#       {%- for s in states
#         | selectattr('entity_id','search','calendar.ical_*')
#         | rejectattr('entity_id', 'search', 'calendar.ical_home_assistant')
#         | rejectattr('entity_id', 'search', 'calendar.ical_test')
#         | list %}
#         - {{s.entity_id }}
#       {%- endfor %}
#   - variables:
#       all_events: >
#         {% raw %}
#         {% set ns = namespace(items=[]) -%}
#         {%- for key, value in agenda.items() %}
#           {%- for event in value.events %}
#             {% set temp = [{'start': event.start, 'end': event.end, 'calendar': state_attr(key, 'friendly_name'), 'summary': event.summary, 'location': event.location if event.location is defined else 'No Location'}] %}
#             {% set ns.items = ns.items + temp %}
#           {%- endfor %}
#         {%- endfor %}
#         {{ ns.items }}
#         {% endraw %}
#       events: >
#         {% raw %}{{ all_events | list }}{% endraw %}
# sensor:
#   - name: "[Upcoming Sport] Next 24 Hours"
#     unique_id: upcoming_sport_next_24_hours
#     state: >
#       {% raw %}{{ events | count }}{% endraw %}
#     state_class: measurement
#     unit_of_measurement: Events
#     icon: mdi:calendar
#     attributes:
#       category: sport
#       scheduled_events: >
#         {% raw %}{{ events | sort(attribute='start') }}{% endraw %}

trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/6"
  - platform: calendar
    event: end
    entity_id: calendar.ical_extreme_e
  - platform: calendar
    event: end
    entity_id: calendar.ical_nascar_cup_series
  - platform: calendar
    event: end
    entity_id: calendar.ical_nascar_xfinity_series
  - platform: calendar
    event: end
    entity_id: calendar.ical_anaheim_ducks
  - platform: calendar
    event: end
    entity_id: calendar.ical_new_england_patriots
  - platform: calendar
    event: end
    entity_id: calendar.ical_new_york_yankees
  - platform: calendar
    event: end
    entity_id: calendar.ical_newcastle_knights
  - platform: calendar
    event: end
    entity_id: calendar.ical_nsw_waratahs
  - platform: calendar
    event: end
    entity_id: calendar.ical_manchester_united
  - platform: calendar
    event: end
    entity_id: calendar.ical_wec
  - platform: calendar
    event: end
    entity_id: calendar.ical_misc_motorsport
  - platform: calendar
    event: end
    entity_id: calendar.ical_wallabies
  - platform: calendar
    event: end
    entity_id: calendar.ical_socceroos
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_kings
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_sixers
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_sixers_women
  - platform: calendar
    event: end
    entity_id: calendar.ical_cricket_australia_womens
  - platform: calendar
    event: end
    entity_id: calendar.ical_cricket_australia_mens
  - platform: calendar
    event: end
    entity_id: calendar.ical_icc_cricket_mens
  - platform: calendar
    event: end
    entity_id: calendar.ical_swifts
  - platform: calendar
    event: end
    entity_id: calendar.ical_international_rugby_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_indycar
  - platform: calendar
    event: end
    entity_id: calendar.ical_gt_world_challenge_asia
  - platform: calendar
    event: end
    entity_id: calendar.ical_formula_2
  - platform: calendar
    event: end
    entity_id: calendar.ical_formula_3
  - platform: calendar
    event: end
    entity_id: calendar.ical_gt_world_challenge_australia
  - platform: calendar
    event: end
    entity_id: calendar.ical_tcr_australia
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_swans_vfl
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_swans_aflw
  - platform: calendar
    event: end
    entity_id: calendar.ical_toronto_maple_leafs
  - platform: calendar
    event: end
    entity_id: calendar.ical_manchester_united_women
  - platform: calendar
    event: end
    entity_id: calendar.ical_newcastle_knights_nrlw
  - platform: calendar
    event: end
    entity_id: calendar.ical_nrlw_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_fc_women
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_fc
  - platform: calendar
    event: end
    entity_id: calendar.ical_aflw_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_formula_e
  - platform: calendar
    event: end
    entity_id: calendar.ical_bayern_munich
  - platform: calendar
    event: end
    entity_id: calendar.ical_nrl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_sydney_swans
  - platform: calendar
    event: end
    entity_id: calendar.ical_dtm
  - platform: calendar
    event: end
    entity_id: calendar.ical_supercars
  - platform: calendar
    event: end
    entity_id: calendar.ical_imsa
  - platform: calendar
    event: end
    entity_id: calendar.ical_wrc
  - platform: calendar
    event: end
    entity_id: calendar.ical_worldsbk
  - platform: calendar
    event: end
    entity_id: calendar.ical_btcc
  - platform: calendar
    event: end
    entity_id: calendar.ical_formula_1
  - platform: calendar
    event: end
    entity_id: calendar.ical_nba_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_nfl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_motogp
  - platform: calendar
    event: end
    entity_id: calendar.ical_nhl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_afl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_igtc
  - platform: calendar
    event: end
    entity_id: calendar.ical_mls_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_alm_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_alw_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_premier_league_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_bbl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_wbbl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_nascar_truck_series
  - platform: calendar
    event: end
    entity_id: calendar.ical_mlb_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_wrexham_afc
  - platform: calendar
    event: end
    entity_id: calendar.ical_matildas
  - platform: calendar
    event: end
    entity_id: calendar.ical_laliga_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_nbl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_super_rugby_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_wsl_all_teams
  - platform: calendar
    event: end
    entity_id: calendar.ical_uefa_champions_league
  - platform: calendar
    event: end
    entity_id: calendar.ical_uefa_europa_league
  - platform: calendar
    event: end
    entity_id: calendar.ical_sailgp
  - platform: event
    event_type: event_template_reloaded
action:
  - service: calendar.get_events
    data:
      duration:
        hours: 24
    response_variable: agenda
    target:
      entity_id:
        - calendar.ical_extreme_e
        - calendar.ical_nascar_cup_series
        - calendar.ical_nascar_xfinity_series
        - calendar.ical_anaheim_ducks
        - calendar.ical_new_england_patriots
        - calendar.ical_new_york_yankees
        - calendar.ical_newcastle_knights
        - calendar.ical_nsw_waratahs
        - calendar.ical_manchester_united
        - calendar.ical_wec
        - calendar.ical_misc_motorsport
        - calendar.ical_wallabies
        - calendar.ical_socceroos
        - calendar.ical_sydney_kings
        - calendar.ical_sydney_sixers
        - calendar.ical_sydney_sixers_women
        - calendar.ical_cricket_australia_womens
        - calendar.ical_cricket_australia_mens
        - calendar.ical_icc_cricket_mens
        - calendar.ical_swifts
        - calendar.ical_international_rugby_all_teams
        - calendar.ical_indycar
        - calendar.ical_gt_world_challenge_asia
        - calendar.ical_formula_2
        - calendar.ical_formula_3
        - calendar.ical_gt_world_challenge_australia
        - calendar.ical_tcr_australia
        - calendar.ical_sydney_swans_vfl
        - calendar.ical_sydney_swans_aflw
        - calendar.ical_toronto_maple_leafs
        - calendar.ical_manchester_united_women
        - calendar.ical_newcastle_knights_nrlw
        - calendar.ical_nrlw_all_teams
        - calendar.ical_sydney_fc_women
        - calendar.ical_sydney_fc
        - calendar.ical_aflw_all_teams
        - calendar.ical_formula_e
        - calendar.ical_bayern_munich
        - calendar.ical_nrl_all_teams
        - calendar.ical_sydney_swans
        - calendar.ical_dtm
        - calendar.ical_supercars
        - calendar.ical_imsa
        - calendar.ical_wrc
        - calendar.ical_worldsbk
        - calendar.ical_btcc
        - calendar.ical_formula_1
        - calendar.ical_nba_all_teams
        - calendar.ical_nfl_all_teams
        - calendar.ical_motogp
        - calendar.ical_nhl_all_teams
        - calendar.ical_afl_all_teams
        - calendar.ical_igtc
        - calendar.ical_mls_all_teams
        - calendar.ical_alm_all_teams
        - calendar.ical_alw_all_teams
        - calendar.ical_premier_league_all_teams
        - calendar.ical_bbl_all_teams
        - calendar.ical_wbbl_all_teams
        - calendar.ical_nascar_truck_series
        - calendar.ical_mlb_all_teams
        - calendar.ical_wrexham_afc
        - calendar.ical_matildas
        - calendar.ical_laliga_all_teams
        - calendar.ical_nbl_all_teams
        - calendar.ical_super_rugby_all_teams
        - calendar.ical_wsl_all_teams
        - calendar.ical_uefa_champions_league
        - calendar.ical_uefa_europa_league
        - calendar.ical_sailgp
  - variables:
      all_events: >
        {% set ns = namespace(items=[]) -%}
        {%- for key, value in agenda.items() %}
          {%- for event in value.events %}
            {% set temp = [{'start': event.start, 'end': event.end, 'calendar': state_attr(key, 'friendly_name'), 'summary': event.summary, 'location': event.location if event.location is defined else 'No Location'}] %}
            {% set ns.items = ns.items + temp %}
          {%- endfor %}
        {%- endfor %}
        {{ ns.items }}
      events: >
        {{ all_events | list }}
sensor:
  - name: "[Upcoming Sport] Next 24 Hours"
    unique_id: upcoming_sport_next_24_hours
    state: >
      {{ events | count }}
    state_class: measurement
    unit_of_measurement: Events
    icon: mdi:calendar
    attributes:
      category: sport
      scheduled_events: >
        {{ events | sort(attribute='start') }}
