---
homeassistant:
  customize_glob:
    package.node_anchors:
      customize: &customize
        package: "monitordocker"
    "*monitordocker*":
      <<: *customize

monitor_docker:
  - name: TBSH1_monitordocker
    url: http://192.168.1.91:2375
    scan_interval: 60
    buttonenabled: true
    monitored_conditions:
      - allinone

  - name: TBSH2_monitordocker
    url: http://192.168.1.131:2375
    scan_interval: 60
    buttonenabled: true
    monitored_conditions:
      - allinone

  - name: TBSH3_monitordocker
    url: http://192.168.1.132:2375
    scan_interval: 60
    monitored_conditions:
      - allinone

  - name: TBSH5_monitordocker
    url: http://192.168.1.133:2375
    scan_interval: 60
    buttonenabled: true
    monitored_conditions:
      - allinone

  - name: PI4SRV_monitordocker
    url: http://192.168.1.64:2375
    scan_interval: 60
    buttonenabled: true
    monitored_conditions:
      - allinone
