---
resource: https://corquaid.github.io/international-space-station-APIs/JSON/people-in-space.json
scan_interval: 300
sensor:
  name: iss_dockedspacecraft
  unique_id: iss_dockedspacecraft
  value_template: "{{ value_json.number }}"
  icon: mdi:space-station
  state_class: measurement
  json_attributes:
    - iss_expedition
    - expedition_patch
    - expedition_url
    - expedition_image
    - expedition_start_date
    - expeditionn_end_date
    - people
