---
binary_sensor:
  - name: "[Alerts] Disabled"
    unique_id: alerts_disabled
    icon: mdi:alert-decagram-outline
    device_class: problem
    state: >
      {{ states.alert
        |selectattr('state','eq','off')
        |list|count > 0 }}
    attributes:
      category: alerts
      entity_id: >
        {{ expand(states.alert)
          |selectattr('state','eq','off')
          |map(attribute='entity_id')
          |list|sort}}

  - name: "alerts_wan_offline"
    unique_id: alert_wan_offline
    icon: mdi:wan
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_wan','off')
          and is_state('input_boolean.alerts_network','on') }}
    attributes:
      category: network

  - name: "alerts_backup"
    unique_id: alerts_backup
    icon: mdi:cloud-upload-outline
    device_class: problem
    delay_on: 60
    state: >
      {% if is_state('input_boolean.alerts_ha','on') %}
        {{ states('sensor.backup_size_status') in ['severe','critical','error']
            or is_state('binary_sensor.home_assistant_google_drive_backup_running','off') }}
      {% endif %}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_weatherflow_cloud"
    unique_id: alerts_connect_weatherflow_cloud
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_weatherflow_cloud','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_weatherflow_local"
    unique_id: alerts_connect_weatherflow_local
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_weatherflow_local','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_pirateweather"
    unique_id: alerts_connect_pirateweather
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_pirateweather','off')
          and is_state('input_boolean.alerts_weather','on') }}

  - name: "alerts_connect_openuv"
    unique_id: alerts_connect_openuv
    icon: mdi:weather-sunny-alert
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_openuv','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_waqi"
    unique_id: alerts_connect_wqai
    icon: mdi:smog
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_waqi','off')
          and is_state('input_boolean.alerts_weather','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_sungather"
    unique_id: alerts_sungather
    icon: mdi:solar-power-variant-outline
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.sungather_running','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_adguard"
    unique_id: alerts_connect_adguard
    icon: mdi:shield-account
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_adguard','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_apple_tv"
    unique_id: alerts_connect_apple_tv
    icon: mdi:apple
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_apple_tv','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_bureau_of_meteorology"
    unique_id: alerts_connect_bureau_of_meteorology
    icon: mdi:weather-lightning-rainy
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_bureau_of_meteorology','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_eufy_security"
    unique_id: alerts_connect_eufy_security
    icon: mdi:cctv-off
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_eufy_security','off')
          and is_state('input_boolean.alerts_camera','on') }}
    attributes:
      category: camera

  - name: "alerts_connect_hdhomerun"
    unique_id: alerts_connect_hdhomerun
    icon: mdi:television-box
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_hdhomerun','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_lg_smartthinq"
    unique_id: alerts_connect_lg_smartthinq
    icon: si:lg
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_lg_smartthinq','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_solcast_solar"
    unique_id: alerts_connect_solcast_solar
    icon: mdi:solar-power-variant
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_solcast_solar','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_forecast_solar"
    unique_id: alerts_connect_forecast_solar
    icon: mdi:solar-power-variant
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_forecast_solar','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_spotify"
    unique_id: alerts_connect_spotify
    icon: mdi:spotify
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_spotify','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_synology"
    unique_id: alerts_connect_synology
    icon: mdi:nas
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_synology','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_unifi"
    unique_id: alerts_connect_unifi
    icon: mdi:wifi
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_unifi','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_connect_speedtest"
    unique_id: alerts_connect_speedtest
    icon: mdi:speedometer
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_speedtest','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_nabucasa_remoteui"
    unique_id: alerts_nabucasa_remoteui
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.remote_ui','off')
          and is_state('input_boolean.alerts_ha','on')
          and is_state('input_boolean.ha_startup_pending','off') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_docker_containersoff"
    unique_id: alerts_docker_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 300
    state: >
      {{ (is_state('binary_sensor.docker_tbsh1_containersoff','on')
          or is_state('binary_sensor.docker_tbsh2_containersoff','on')
          or is_state('binary_sensor.docker_tbsh3_containersoff','on')
          or is_state('binary_sensor.docker_tbsh5_containersoff','on')
          or is_state('binary_sensor.docker_pi4srv_containersoff','on'))
          and is_state('input_boolean.alerts_docker_containers_off','on') }}
    attributes:
      category: docker

  - name: "alerts_zigbee2mqtt_offline"
    unique_id: alerts_zigbee2mqtt_offline
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.status_zigbee2mqtt','off')
          and is_state('input_boolean.alerts_ha','on')
          and is_state('input_boolean.ha_startup_pending','off') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_proxmox_nodesoff"
    unique_id: alerts_proxmox_nodesoff
    icon: si:proxmox
    device_class: problem
    delay_on: 300
    state: >
      {{ (is_state('binary_sensor.node_pvetbsh_status','off')
          or is_state('binary_sensor.node_pvenuc_status','off')
          or is_state('binary_sensor.node_pvenuc2_status','off')) }}
    attributes:
      category: proxmox

  - name: "alerts_ical"
    unique_id: alerts_ical
    icon: mdi:calendar
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_ical','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_bluetooth"
    unique_id: alerts_bluetooth
    icon: mdi:bluetooth
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_bluetooth','off')
          and is_state('input_boolean.alerts_bluetooth','on') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_cloudflare_tunnel"
    unique_id: alerts_cloudflare_tunnel
    icon: si:cloudflare
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.cloudflare_tunnel_status','on')
          and is_state('input_boolean.alerts_ha','on')  }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_co2_signal"
    unique_id: alerts_co2_signal
    icon: mdi:smog
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_co2_signal','off')
          and is_state('input_boolean.alerts_ha','on')  }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_blitzortung"
    unique_id: alerts_blitzortung
    icon: mdi:flash-alert
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_blitzortung','off')
          and is_state('input_boolean.alerts_weather','on')  }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_flightradar24"
    unique_id: alerts_flightradar24
    icon: mdi:airplane-alert
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_flightradar24','off')
          and is_state('input_boolean.alerts_ha','on')  }}
    attributes:
      category: homeassistant_connectivity
