---
binary_sensor:
  - name: "[Alerts] Disabled"
    unique_id: alerts_disabled
    icon: mdi:alert-decagram-outline
    device_class: problem
    state: >
      {{ states.alert
        |selectattr('state','eq','off')
        |list|count > 0 }}
    attributes:
      category: alerts
      entity_id: >
        {{ expand(states.alert)
          |selectattr('state','eq','off')
          |map(attribute='entity_id')
          |list|sort}}

  - name: "alerts_wan_offline"
    unique_id: alert_wan_offline
    icon: mdi:wan
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.ha_connected_integration_wan','off')
          and is_state('input_boolean.alerts_network','on') }}
    attributes:
      category: network

  - name: "alerts_backup"
    unique_id: alerts_backup
    icon: mdi:cloud-upload-outline
    device_class: problem
    delay_on: 60
    state: >
      {% if is_state('input_boolean.alerts_ha','on') %}
        {{ states('sensor.backup_size_status') in ['severe','critical','error']
            or is_state('binary_sensor.home_assistant_google_drive_backup_running','off') }}
      {% endif %}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_ha_connected_integration"
    unique_id: alerts_ha_connected_integration
    icon: mdi:sync-alert
    device_class: problem
    delay_on: 120
    state: >
      {{states
          |selectattr('entity_id','search','binary_sensor.ha_connected_integration_*')
          |selectattr('state','eq','off')
          |map(attribute='entity_id')
          |list | count > 0
          and is_state('input_boolean.alerts_ha','on')  }}
    attributes:
      category: homeassistant_connectivity
      impacted_integrations: >
        {{states
            |selectattr('entity_id','search','binary_sensor.ha_connected_integration_*')
            |selectattr('state','eq','off')
            |map(attribute='entity_id')
            |list|sort|replace('binary_sensor.ha_connected_integration_','') }}

  - name: "alerts_sungather"
    unique_id: alerts_sungather
    icon: mdi:solar-power-variant-outline
    device_class: problem
    delay_on: 300
    state: >
      {{ is_state('binary_sensor.sungather_running','off')
          and is_state('input_boolean.alerts_ha','on') }}
    attributes:
      category: homeassistant

  - name: "alerts_nabucasa_remoteui"
    unique_id: alerts_nabucasa_remoteui
    device_class: problem
    delay_on: 60
    state: >
      {{ is_state('binary_sensor.remote_ui','off')
          and is_state('input_boolean.alerts_ha','on')
          and is_state('input_boolean.ha_startup_pending','off') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_docker_containersoff"
    unique_id: alerts_docker_containersoff
    icon: mdi:docker
    device_class: problem
    delay_on: 300
    state: >
      {{ (is_state('binary_sensor.docker_tbsh1_containersoff','on')
          or is_state('binary_sensor.docker_tbsh2_containersoff','on')
          or is_state('binary_sensor.docker_tbsh3_containersoff','on')
          or is_state('binary_sensor.docker_tbsh5_containersoff','on')
          or is_state('binary_sensor.docker_pi4srv_containersoff','on'))
          and is_state('input_boolean.alerts_docker_containers_off','on') }}
    attributes:
      category: docker

  - name: "alerts_zigbee2mqtt_offline"
    unique_id: alerts_zigbee2mqtt_offline
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.status_zigbee2mqtt','off')
          and is_state('input_boolean.alerts_ha','on')
          and is_state('input_boolean.ha_startup_pending','off') }}
    attributes:
      category: homeassistant_connectivity

  - name: "alerts_proxmox_nodesoff"
    unique_id: alerts_proxmox_nodesoff
    icon: si:proxmox
    device_class: problem
    delay_on: 300
    state: >
      {{ (is_state('binary_sensor.node_pvetbsh_status','off')
          or is_state('binary_sensor.node_pvenuc_status','off')
          or is_state('binary_sensor.node_pvenuc2_status','off')) }}
    attributes:
      category: proxmox

  # - name: "alerts_bluetooth"
  #   unique_id: alerts_bluetooth
  #   icon: mdi:bluetooth
  #   device_class: problem
  #   delay_on: 120
  #   state: >
  #     {{ is_state('binary_sensor.ha_connected_integration_bluetooth','off')
  #         and is_state('input_boolean.alerts_bluetooth','on') }}
  #   attributes:
  #     category: homeassistant_connectivity

  - name: "alerts_cloudflare_tunnel"
    unique_id: alerts_cloudflare_tunnel
    icon: si:cloudflare
    device_class: problem
    delay_on: 120
    state: >
      {{ is_state('binary_sensor.cloudflare_tunnel_status','on')
          and is_state('input_boolean.alerts_ha','on')  }}
    attributes:
      category: homeassistant
