---
sensor:
  - platform: rest
    name: Hass Main config
    resource: !secret hass_api_config_url
    authentication: basic
    value_template: >
      {{ value_json.version }}
    json_attributes:
      - components
      - unit_system
      - config_dir
      - config_source
      - version
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: rest
    name: Hass.io Info
    resource: !secret hassio_api_info_url
    authentication: basic
    value_template: >
      {{ value_json.result }}
    json_attributes:
      - data
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: rest
    name: hassos_installed_version
    resource: !secret hassio_api_info_url
    authentication: basic
    value_template: >
      {{ value_json.data.hassos }}
    headers:
      Content-Type: application/json
      Authorization: !secret ha_api_llat
      User-Agent: Home Assistant REST sensor

  - platform: template
    sensors:
      count_all_components:
        friendly_name: "All Components"
        icon_template: mdi:code-tags
        value_template: "{{ states.sensor.hass_main_config.attributes.components | count }}"
